import type { NextPage } from "next";
import Head from "next/head";
import { HeadingL1 } from "src/modules/shared/components/HeadingL1";
import { HeadingL2 } from "src/modules/shared/components/HeadingL2";

// Create a Title component that'll render an <h1> tag with some styles

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeadingL1>
        <em>TECH</em> zone
      </HeadingL1>
    </div>
  );
};

export default Home;
