import type { NextPage } from 'next';
import Head from 'next/head';

import { Heading1 } from 'src/modules/shared/components/base/Heading1';
import { Text1 } from 'src/modules/shared/components/base/Text1';
import { NavBar } from 'src/modules/shared/components/NavBar';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/favicon.svg" />
      </Head>

      <NavBar />

      <Text1 variant="allCaps">Explore the</Text1>

      <Heading1>
        <em>TECH</em> zone
      </Heading1>

      <Text1>
        Here you’ll be able to redeem all of your hard-earned Aeropoints and
        exchange them for cool tech.
      </Text1>
    </div>
  );
};

export default Home;
